on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'The name of the environment to be deployed'     
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - uat
        - prod
permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: .,terraform,terraform/dev,terraform/modules
        output-file: terraform_docs.md
        output-method: inject
        git-push: "true"
